---
abstract: 'fix the file permissions in your Git repository with Dist::Zilla'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Dist::Zilla::Plugin::Git::GatherDir: '0'
  Test::DZil: '0'
  Test::Fatal: '0'
  Test::More: '0'
  Test::TempDir::Tiny: '0'
  autodie: '0'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150010'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Git-FilePermissions
no_index:
  directory:
    - t
    - xt
provides:
  Dist::Zilla::Plugin::Git::FilePermissions:
    file: lib/Dist/Zilla/Plugin/Git/FilePermissions.pm
    version: '1.000'
requires:
  Dist::Zilla::Role::BeforeBuild: '0'
  Git::Wrapper: '0'
  Moose: '2.1203'
  Path::Tiny: '0'
  Safe::Isa: '0'
  Try::Tiny: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Dist-Zilla-Plugin-Git-FilePermissions/issues
  homepage: https://github.com/skirmess/Dist-Zilla-Plugin-Git-FilePermissions
  repository: https://github.com/skirmess/Dist-Zilla-Plugin-Git-FilePermissions.git
version: '1.000'
x_serialization_backend: 'YAML::Tiny version 1.70'
